name: Android APK (Release, Signed)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-release-signed:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PATH: app/keystore.jks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Decode keystore from secret
        shell: bash
        run: |
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/${{ env.KEYSTORE_PATH }}

      - name: Create key.properties
        run: |
          cat > android/key.properties <<'EOF'
          storeFile=${{ env.KEYSTORE_PATH }}
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          keyPassword=${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
          EOF

      - name: Build release APK (signed)
        run: flutter build apk --release

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk